theme: jekyll-theme-minimal
title: National Negro Health works in the HathiTrust Digital Library
description: Data and contextual information for “National Negro Health works in the HathiTrust Digital Library,” a workset curated by Kim Gallon in collaboration with the HathiTrust Research Center with generous support from the Mellon Foundation.